### ISSUE TITLE
Duplicate data exists

### ISSUE THREAD

**Issue by zhiweihu1103** [itsnamgyu/reasoning-teacher#10]
I saw that there are multiple identical duplicate data in a data set. Taking multiarith.json as an example, the sample_index values ​​are 344 and 354, which are exactly the same two samples. Can you explain it?

**Comment by itsnamgyu** [comment]
Thank you for pointing this out! Can you tell me which file it is specifically? (the directory name)

**Comment by zhiweihu1103** [comment]
> Thank you for pointing this out! Can you tell me which file it is specifically? (the directory name)
The file named multiarith.json in dataset.tar.gz in https://drive.google.com/drive/folders/1C6kah3WV36N8omlUl-TeU9tsJADZNaJV

**Comment by itsnamgyu** [comment]
Thanks for the clarification. I actually took the datasets from https://github.com/kojima-takeshi188/zero_shot_cot/blob/main/dataset/MultiArith/MultiArith.json and it appears that the original file also has the same duplicate data.

It may simply be that the original dataset contains duplicates. I can't investigate this now, but if you find out something, then I'll gladly add some documentation. I will not able to run extra experiments for the time-being.

**Comment by itsnamgyu** [comment]
I will close this issue for now. Please let me know if you have any findings!
