### ISSUE TITLE
How does "complexion_data" come from?

### ISSUE THREAD

**Issue by BingyuanZhang** [itsnamgyu/reasoning-teacher#11]
I currently have a dataset of cqa with output from llm as a label, with fields such as "input", "rational", "label", and "llm label". How can I obtain "complexion_data"?
Is there any code that can be used?

**Comment by itsnamgyu** [comment]
I think you will have to write some custom code for this, based on the format of our `completion_data`. I think this should be simple python code using the `json` library.
