### ISSUE TITLE
How can I load a saved ckpt file using huggingface's from_pretrained?

### ISSUE THREAD

**Issue by Zzl3** [itsnamgyu/reasoning-teacher#14]
After training the fine-tuning with my own dataset, is it possible to convert the saved downloaded cpkt to a file format that can be used with the huggingface interface?

**Comment by itsnamgyu** [comment]
I'm pretty sure it is possible but I haven't tried that before. I think this might be helpful.

https://huggingface.co/docs/transformers/en/model_sharing
