### ISSUE TITLE
How accurate is the answer rate when using the teacher model to generate reasoning cot for the CommonsenseQA dataset?

### ISSUE THREAD

**Issue by JiayiFu** [itsnamgyu/reasoning-teacher#3]
Hi,
   Thank you for open-sourcing the code and related data.  Fine-tune-CoT is a great work and I am some experiments recently while referencing your paper.
   I have been attempting to utilize the OpenAI ChatGPT API to generate fine-tuned data for the student model, following the methods in your paper. I have tried constructing prompts to guide ChatGPT in generating the reasoning process. However, I have observed a high error rate in the generated answers. For instance: the query I sent to ChatGPT API is:
`Q: Where can someone store extra sheets of paper? Answer choices:(A) printer,(B) box,(C) cutting and folding,(D) cabinet,(E) office. A: Let's think step by step.`
The return answer from API is : `A printer can hold some sheets of paper, but it may not be the best choice for storing extra sheets. A box, cabinet, or office can be used to store extra sheets of paper more effectively. Cutting and folding is not a place; it is a process, so this option is not suitable for storing extra sheets of paper. Based on these points, both (B) box and (D) cabinet would be suitable for storing extra sheets of paper.` . But the reference answer key is `E: office`. So ChatGPT gives me a wrong answer and this situation is quite common. If I proceed with answer filtering, it may result in lower data effectiveness.
    Have you encountered similar issues with the CommonsenseQA dataset? Do you have any suggestions for improving the accuracy of the generated answer results? 
   By the way, will you open source the data used to train your student models anytime soon?  Thanks again!

**Comment by itsnamgyu** [comment]
As shown in Table 1 of our paper, the accuracy of the teacher model (in our case, `text-davinci-002`) is 61.75%–not always very accurate. It's pointed out in Kojima et al 2022 (https://arxiv.org/abs/2205.11916) that the model sometimes outputs multiple answers, similar to what you've found. We also found that many of the question/answers are quite subjective at times, which might contribute to the low accuracy.

We will upload _all_ the data we have and make final updates to the code within 1 week. I'll let you know on this thread :)

**Comment by itsnamgyu** [comment]
+ I haven't really thought about how to increase the accuracy of the teacher on CommonSenseQA. You could consider using self-consistency (https://arxiv.org/abs/2203.11171), or try optimizing the zero-shot prompt for the specific task (maybe try to inspect the raw data and identify what kind of subjective biases went into the selection of answers).

**Comment by JiayiFu** [comment]
Thanks for your reply!

**Comment by itsnamgyu** [comment]
@JiayiFu  The full raw experimental data is available for download! Check out the README and spread the word :)
