### ISSUE TITLE
Some bugs in example_oai_finetune_cot.ipynb

### ISSUE THREAD

**Issue by CRLqinliang** [itsnamgyu/reasoning-teacher#4]
Thanks for opening the source of your code.
Recently, when I try to run your code file **example_oai_finetune_cot.ipynb** at the command `fetch_model_ids()`
I got this 

> FileNotFoundError                         Traceback (most recent call last)
> [/home/qinliang/Desktop/LLM_Reasoning_teacher/reasoning-teacher/notebooks/example_oai_finetune_cot.ipynb](https://file+.vscode-resource.vscode-cdn.net/home/qinliang/Desktop/LLM_Reasoning_teacher/reasoning-teacher/notebooks/example_oai_finetune_cot.ipynb) Cell 25 in ()
> ----> [1](vscode-notebook-cell:/home/qinliang/Desktop/LLM_Reasoning_teacher/reasoning-teacher/notebooks/example_oai_finetune_cot.ipynb#X33sZmlsZQ%3D%3D?line=0) fetch_model_ids()
> 
> File [~/Desktop/LLM_Reasoning_teacher/reasoning-teacher/src/oai/utils/api_wrapper.py:101](https://file+.vscode-resource.vscode-cdn.net/home/qinliang/Desktop/LLM_Reasoning_teacher/reasoning-teacher/notebooks/~/Desktop/LLM_Reasoning_teacher/reasoning-teacher/src/oai/utils/api_wrapper.py:101), in fetch_model_ids()
>      99 with open(FINETUNE_IDS_PATH) as f:
>     100     finetune_ids = json.load(f)
> --> 101 with open(MODEL_IDS_PATH) as f:
>     102     model_ids = json.load(f)
>     104 model_keys_to_fetch = []
> 
> FileNotFoundError: [Errno 2] No such file or directory: '[/home/qinliang/Desktop/LLM_Reasoning_teacher/reasoning-teacher/saved/openai_metadata/model_ids.json](https://file+.vscode-resource.vscode-cdn.net/home/qinliang/Desktop/LLM_Reasoning_teacher/reasoning-teacher/saved/openai_metadata/model_ids.json)'

We didn't build the model_ids.json, therefore we couldn't run this command.
So could you please check it ? @itsnamgyu 
Thx.

**Comment by itsnamgyu** [comment]
Sorry for the delay, it should work now. Thanks for the feedback!

Those metadata files should be created by the code itself. Looks like there was a directory-missing issue when creating the files in a fresh project.
