### ISSUE TITLE
 to some extent the same as the paper "large language models can self-improve"

### ISSUE THREAD

**Issue by leileilin** [itsnamgyu/reasoning-teacher#5]

**Comment by itsnamgyu** [comment]
Yes, there are many similar papers that were published near to or after our publication!

The paper you mention is one of the oldest ones that we are aware of (they have a very similar experiment in their Appendix), as well as "Explanations from Large Language Models Make Small Reasoners Better".

All the papers have unique quirks in methodology, findings, range of tasks, etc.

I personally would recommend the following for their interesting perspective on multi-task learning and excellent methodology, respectively.

- Distilling Step-by-Step! Outperforming Larger Language Models with Less Training Data and Smaller Model Sizes
- SCOTT: Self-Consistent Chain-of-Thought Distillation
